#!/bin/sh

database_ready() {
python << END
import sys
import psycopg2
try:
    psycopg2.connect(database="${POSTGRES_DB}",
                      user="${POSTGRES_USER}",
                      password="${POSTGRES_PASSWORD}",
                      host="${POSTGRES_HOST}",
                      port="${POSTGRES_PORT}")
except Exception as e:
    print(f'{e}')
    sys.exit(-1)
sys.exit(0)
END
}
until database_ready; do
  >&2 echo 'Waiting for Postgres to become available...'
  sleep 5
done
>&2 echo 'Postgres is available'

python manage.py migrate
python manage.py runserver 0.0.0.0:8000