version: "3.8"

services:

  django:
    container_name: 'django'
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_agrotool
    restart: on-failure:5
    command: /start
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgresql

  postgresql:
    container_name: 'postgresql'
    image: postgres:14
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: agrotool_db
    ports:
      - 5432:5432
    volumes:
      - agrotool_pg:/var/lib/postgresql/data

volumes:
  agrotool_pg: