# Generated by Django 4.2.7 on 2023-11-07 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hectare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150, verbose_name='Codigo')),
            ],
            options={
                'verbose_name': 'Hectarea',
                'verbose_name_plural': 'Hectareas',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150, verbose_name='Codigo')),
                ('tree_age', models.IntegerField(verbose_name='Edad de arboles')),
                ('species', models.CharField(max_length=150, verbose_name='Especie')),
                ('objetive', models.CharField(blank=True, choices=[('oil', 'Aceite'), ('olive', 'Aceitunas')], max_length=5, null=True, verbose_name='Objetivo')),
                ('hectare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantation.hectare')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
    ]
