# Generated by Django 4.2.7 on 2023-11-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad'),
        ),
    ]
