# Generated by Django 4.2.7 on 2023-11-09 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plantation', '0003_batch_planting_date_batch_pruning_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='planting_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de plantación'),
        ),
    ]
