# Generated by Django 4.2.7 on 2023-11-07 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('util', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffEquipment',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='util.basemodel')),
            ],
            options={
                'verbose_name': 'Equipo para personal',
                'verbose_name_plural': 'Equipos para personal',
            },
            bases=('util.basemodel',),
        ),
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='util.basemodel')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
            bases=('util.basemodel',),
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='util.basemodel')),
            ],
            options={
                'verbose_name': 'Herramienta',
                'verbose_name_plural': 'Herramientas',
            },
            bases=('util.basemodel',),
        ),
    ]
