# Generated by Django 4.2.7 on 2023-11-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='codigo',
            field=models.IntegerField(verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
    ]
